### ISSUE TITLE
10.15.3 unsupported

### ISSUE THREAD

**Issue by lmentor** [chris1111/Wireless-Ralink-Panel-Utility#1]
update 10.15.3 then 360wifi can't work

**Comment by chris1111** [comment]
> update 10.15.3 then 360wifi can't work

Chek your system its work here!
 Is Support

![Capture d’écran, le 2020-01-29 à 22 33 13](https://user-images.githubusercontent.com/6248794/73417855-98ffc900-42e7-11ea-933b-e8fff5ad9225.png)
