### ISSUE TITLE
I cannot connect to the internet.

### ISSUE THREAD

**Issue by tolgasonkaya** [chris1111/Wireless-Ralink-Panel-Utility#2]
Hello Chris. I need your help. I have a USB WiFi card give the chip MT7601. I use your program but I cannot assign IP and I can not access the internet, please help.

<a href="https://hizliresim.com/zyRAq9"><img src="https://i.hizliresim.com/zyRAq9.jpg"></a>
<a href="https://hizliresim.com/GGnYXV"><img src="https://i.hizliresim.com/GGnYXV.jpg"></a>
<a href="https://hizliresim.com/yjdM97"><img src="https://i.hizliresim.com/yjdM97.png"></a>

**Comment by chris1111** [comment]
Reboot the macOS and Activate the network on connect order, use Light mode to see the network on the panel

**Comment by tolgasonkaya** [comment]
I restarted Mac Os but still the problem is not resolved.I have also tested the same problem in Mojave, and there are many people who have the same problem. My english is bad sorry

**Comment by chris1111** [comment]
I told you using Light mode to see the network in the panel then activate

Follow the video correctly

**Comment by tolgasonkaya** [comment]
OK. I will try and let you know the result.

**Comment by chris1111** [comment]
See my Video, after Activate I do not open preference system / Network
I reboot the PC then wait a bit and the network is connect

Why open another issue ???
