### ISSUE TITLE
No IP assign

### ISSUE THREAD

**Issue by tolgasonkaya** [chris1111/Wireless-Ralink-Panel-Utility#3]
I shot a video showing the problem, Chris. Help me please

[Ekran-Kayd-2020-02-11-154551.zip](https://github.com/chris1111/Wireless-Ralink-Panel-Utility/files/4189213/Ekran-Kayd-2020-02-11-154551.zip)

**Comment by chris1111** [comment]
See my Video, after Activate I do not open preference system / Network
I reboot the PC then wait a bit and the network is connect
