### ISSUE TITLE
Slow speed and 5G networks not working with Archer T2UH (MT7610U)

### ISSUE THREAD

**Issue by ivin600** [chris1111/Wireless-Ralink-Panel-Utility#5]
Hi,
Im having slow speed with 2.4g networks with my Archer T2UH in Mac OS Catalina.
The 5g networks don't Connect.

Thanks for your work, as this is the only utility to get working my USB wireless with Catalina.

**Comment by chris1111** [comment]
You just have to tell yourself that it's the only one and that it works like that 😃
sorry
